#!/usr/bin/env python
# -*- encoding=utf8 -*-

'''
FileName:   pyconsole
Author:     Fasion Chan
@contact:   fasionchan@gmail.com
@version:   $Id$

Description:

Changelog:

'''

import sys
import rlcompleter

from libase.server.console import (
    run_console_proxy,
    )

if __name__ == '__main__':
    run_console_proxy(*sys.argv[1:])
